### ISSUE TITLE
Peer Review

### ISSUE THREAD

**Issue by zchen6** [juliafarhat/project#2]
1. It would be great if you can add a location map for each restaurant.
2. Maybe you can add a rating point and average dollar spending for each person for each restaurant.

**Comment by zchen6** [comment]
https://github.com/juliafarhat/project/blob/64ac3aeb003ba48110cb34e01d900ac559205bf1/brazilian.html#L59-61
add some images here maybe?

**Comment by zchen6** [comment]
https://github.com/juliafarhat/project/blob/64ac3aeb003ba48110cb34e01d900ac559205bf1/contact.html#L72-74
Maybe ask your viewers to choose the best restaurant?

**Comment by juliafarhat** [comment]
Thank you for the suggestions! 

I will definitely look into incorporating some type of map feature and I like the rating points too!
